### PR TITLE
Fix owner/repo fetching

### LINKED ISSUE #6: Error when using scheduled triggers: Cannot read property 'owner' of undefined
Hi,

First of all - a great Action! I really like that you can send updates to a single Slack message, this is really awesome...

Long story short: the Action works great when using pull_request trigger, but when I have a scheduled run, I get this:

Screenshot 2019-12-20 11 23 16

The motivation for us in scheduled triggers is to do CI runs regularly (as some components have more free-floating version locks; this is Terraform code :) )

### PR DESCRIPTION
**Pull request by jplhomer**
## Purpose

Uses a more reliable method of fetching `owner` and `repo` for multiple events.

Fixes #6 

## Important Changes

Nothing major.

## Changelog

- [x] I have updated `CHANGELOG.md` under "Unreleased" with the changes included in this PR.

### CODE REVIEW

**Comment by jatin69** [comment]
@CGeohagan Kindly merge this request and push to the marketplace. I have the same issue, and it should get resolved with this PR.

**Comment by CGeohagan** [comment]
Hey @jatin69 @iniinikoski this has been merged!

**Comment by iniinikoski** [comment]
Excellent, huge thanks @CGeohagan ! :)

**Comment by iniinikoski** [comment]
And - one last wish: please cut a release when you can @CGeohagan :)

**Pull request merged**
